#+title: Solutions to R Programming for Statistics and Data Science
#+startup: overview indent
#+columns: %ITEM %SECTION %CHAPTER
#+PROPERTY: SECTION_ALL 3 5 2

* Exercise 1: Creating an object in R
:PROPERTIES:
:CHAPTER:  8
:SECTION:  3
:END:
Use pemdas and it will work, hence the parantheses in the answer.

#+begin_src R :colnames yes :tangle exercise01.r
  # See LICENSE for details.
  x <- 10:20
  y <- 2 + x
  z <- 3 * y
  answer <- (z - 6) / 3
  data.frame(x, y, z, answer)
#+end_src

* Exercise 2: Data types in R
:PROPERTIES:
:CHAPTER:  11
:SECTION:  3
:END:
Some kind of coercion is applied to transform double to character.

#+begin_src R :tangle exercise02.r
  # See LICENSE for details.
  employee_names <- c(
    "Belinda Johnes",
    "Maria Delar",
    "Math Smith",
    "Matt Williams",
    "Robert Mathews",
    "Julia Walters",
    "Andrea Cheng",
    "July Horitz",
    "Danielle Muller",
    "Esteban Lugo"
  )

  # -> "character"
  typeof(employee_names)

  salary <- c(
    3000,
    NA,
    NA,
    NA,
    NA,
    4000,
    3000,
    5000,
    1000,
    5000
  )

  # -> "double"
  typeof(salary)

  employees <- c(employee_names, salary)

  # -> "character"
  typeof(employees)
#+end_src

* Exercise 3: Coercion rules in R
:PROPERTIES:
:CHAPTER:  13
:SECTION:  3
:END:

I expected the conversion to "TRUE" and "FALSE", as well as the
numeric on logical, as it appears that R strives towards the more
reasonable representation.

There is no straight logical translation from strings to numbers, or
from numbers and strings to logical, thus a hierarchy rises. Or so it
seems.

#+begin_src R :tangle exercise03.r
  # See LICENSE for details.
  employee_names <- c(
    "Belinda Johnes",
    "Maria Delar",
    "Math Smith",
    "Matt Williams",
    "Robert Mathews",
    "Julia Walters",
    "Andrea Cheng",
    "July Horitz",
    "Danielle Muller",
    "Esteban Lugo"
  )

  salary <- c(
    3000,
    NA,
    NA,
    NA,
    NA,
    4000,
    3000,
    5000,
    1000,
    5000
  )

  # my linter says using single letter is bad practice
  yearly_bonus <- c(TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)

  employees <- c(employee_names, salary, yearly_bonus)

  # -> "character"
  typeof(employees)

  # maintain consistency
  coerce.check <- c(salary, yearly_bonus)

  # -> "double"
  typeof(coerce.check)
#+end_src

* Exercise 4: Using functions in R
:PROPERTIES:
:CHAPTER:  15
:SECTION:  3
:END:
#+begin_src R :colnames yes :tangle exercise04.r
  # See LICENSE for details.
  years_of_experience <- c(8, 10, 10, 1, 10, 10, 8, 12, 1, 12)

  # Using data.frame to print table in org mode
  data.frame(
    sum = sum(years_of_experience),
    avg = mean(years_of_experience),
    median = median(years_of_experience),
    length = length(years_of_experience),
    sd = sd(years_of_experience),
    rounded_sd = round(sd(years_of_experience))
  )

  # This is asked
  #print(round(sd(years_of_experience)))
#+end_src

* Exercise 5: The arguments of a function
:PROPERTIES:
:CHAPTER:  17
:SECTION:  3
:END:

The na.rm parameter in median ignores NA values, which if passed become the result.

#+begin_src R :colnames yes :tangle exercise05.r
  # See LICENSE for details.

  # args will only tell you the name of arguments
  args(sample)
  args(median)

  # You should use help with either approach, as it gives you the proper
  # documentation, for example na.rm ignores NA values in regards to
  # salary in the computation.
  ?sample
  ?median


  years_of_experience <- c(8, 10, 10, 1, 10, 10, 8, 12, 1, 12)
  salary <- c(
    3000,
    NA,
    NA,
    NA,
    NA,
    4000,
    3000,
    5000,
    1000,
    5000
  )

  data.frame(
    years_of_experience_median_rmt = median(na.rm = TRUE, years_of_experience),
    years_of_experience_median = median(years_of_experience),
    salary_median_rmt = median(na.rm = TRUE, salary),
    salary_median = median(salary)
  )
#+end_src

* Exercise 6: Building a function in R
:PROPERTIES:
:CHAPTER:  19
:SECTION:  3
:END:
#+begin_src R :tangle exercise06.r
  # See LICENSE for details.
  coin <- c("heads", "tails")
  prob <- c(0.3, 0.7)
  size <- 100

  flip <- function(coin, size, prob) {
    sample(coin, size = size, prob = prob, replace = TRUE)
  }

  print(flip(coin, size, prob))
#+end_src

* Exercise 7: Vector recycling
:PROPERTIES:
:CHAPTER:  24
:SECTION:  4
:END:
The weight gets recycled.
#+begin_src R :tangle exercise07.r
  # See LICENSE for details.

  weight <- c(71, 67, 83, 67)
  height <- c(1.75, 1.81, 1.78, 1.82, 1.97, 2.12, 1.75)

  bmi <- weight / height^2

  print(bmi)
#+end_src

* Exercise 8: Vector attributes - names
:PROPERTIES:
:CHAPTER:  26
:SECTION:  4
:END:
#+begin_src R :tangle exercise08.r
  # See LICENSE for details.
  employee_names <- c(
    "Belinda Johnes",
    "Maria Delar",
    "Math Smith",
    "Matt Williams",
    "Robert Mathews",
    "Julia Walters",
    "Andrea Cheng",
    "July Horitz",
    "Danielle Muller",
    "Esteban Lugo"
  )

  salary <- c(
    3000,
    NA,
    NA,
    NA,
    NA,
    4000,
    3000,
    5000,
    1000,
    5000
  )

  names(salary) <- employee_names

  # the suggested alternative, which I wasn't aware is building directly like so
  salary <- c(
    "Belinda Johnes" = 3000,
    "Maria Delar" = NA,
    "Math Smith" = NA,
    "Matt Williams" = NA,
    "Robert Mathews" = NA,
    "Julia Walters" = 4000,
    "Andrea Cheng" = 3000,
    "July Horitz" = 5000,
    "Danielle Muller" = 1000,
    "Esteban Lugo" = 5000
  )

  names(salary)
#+end_src

* Exercise 9: Indexing and slicing a vector
:PROPERTIES:
:CHAPTER:  29
:SECTION:  4
:END:
#+begin_src R :tangle exercise09.r
  # See LICENSE for details.
  salary <- c(
    3000,
    NA,
    NA,
    NA,
    NA,
    4000,
    3000,
    5000,
    1000,
    5000
  )

  print(salary[6])
  print(salary[-2])
  print(salary[seq(1, 9, 2)])
  print(salary[-(4:6)])
  print(salary[salary > 2000])
#+end_src

* Exercise 10: Vector attributes - dimension
:PROPERTIES:
:CHAPTER:  31
:SECTION:  4
:END:

#+begin_src R :tangle exercise10.r
  # See LICENSE for details.
  s <- seq(2, 30, 2)
  attributes(s)
  class(s)
  dim(s) <- c(3, 5)
  attributes(s)
  class(s)
  dim(s) <- c(1, 3, 5)
  attributes(s)
  class(s)
#+end_src

* Exercise 11: Creating a matrix in R
:PROPERTIES:
:SECTION:  5
:CHAPTER:  34
:END:
#+begin_src R :tangle exercise11.r :colnames yes :rownames yes
  # See LICENSE for details.

  # Just one method using expand.grid as cartesian product, as it seemed more elegant
  pieces <- c(rep("pawn", 8), "rook", "knight", "bishop",  "queen", "king", "bishop", "knight", "rook")
  players <- c("black", "white")

  chess <- expand.grid(x = pieces, y = players)
  colnames(chess) <- c("Piece", "Player")
  chess
#+end_src


